[package]
name = "codestats"
version = "0.1.0"
edition = "2024"
description = "cli tool to quickly analyze the programming languages used in a project"
license = "MIT"

[dependencies]
ignore = "0.4.25"
tabled = "0.20.0"
